### PR TITLE
Corrected spelling mistake.

### PR DESCRIPTION
**Pull request by carmosin**

### CODE REVIEW

**Comment by carmosin** [comment]
Can one of the admins verify this patch?

**Review by helioloureiro — COMMENTED** [review]
ok to test

**Review by carmosin — COMMENTED** [review]
ok to test

**Review by testcarmosin — APPROVED** [review]
ok to test

**Comment by carmosin** [comment]
Can one of the admins verify this patch?

**Review by testcarmosin — APPROVED** [review]
ok to test

**Review by testcarmosin — APPROVED** [review]
ok to test

**Pull request merged**
